fn main() {
    let app_manifest = tauri_build::AppManifest::new().commands(&[
        "get_app_preferences",
        "set_close_to_tray",
        "set_auto_start",
        "set_start_minimized",
        "get_hub_snapshot",
        "update_touch_input",
        "set_touch_config",
        "set_audio_config",
        "audio_control",
        "get_custom_waveform",
        "choose_audio_file",
        "choose_recording_destination",
        "connect_relay",
        "disconnect_relay",
        "refresh_pairing",
        "adjust_intensity",
        "start_output",
        "stop_output",
        "emergency_stop",
        "set_device_channel_source",
        "set_device_channel_source_sync",
        "set_default_source",
        "set_fixed_waveform",
        "import_custom_waveforms",
        "select_custom_waveform",
        "delete_custom_waveform",
        "reorder_custom_waveforms",
        "select_device",
        "set_sync_all_devices",
        "update_safety",
    ]);
    let attributes = tauri_build::Attributes::new().app_manifest(app_manifest);
    tauri_build::try_build(attributes).expect("failed to run Tauri build script");
}
