fn main() {
    const COMMANDS: &[&str] = &[
        "get_app_preferences",
        "set_close_to_tray",
        "set_auto_start",
        "set_start_minimized",
        "get_hub_snapshot",
        "plugin_call",
        "choose_plugin_package",
        "choose_plugin_file",
        "choose_plugin_destination",
        "get_runtime_info",
        "get_mcp_config",
        "parse_waveform_files",
        "get_custom_waveform",
        "get_connections",
        "connect_transport",
        "disconnect_connection",
        "refresh_connection_pairing",
        "set_relay_endpoint",
        "scan_bluetooth",
        "connect_bluetooth",
        "disconnect_bluetooth",
        "get_bluetooth_config",
        "set_bluetooth_config",
        "adjust_intensity",
        "start_output",
        "stop_output",
        "set_device_channel_source",
        "set_device_channel_source_sync",
        "set_default_source",
        "set_fixed_waveform",
        "import_custom_waveforms",
        "select_custom_waveform",
        "delete_custom_waveform",
        "reorder_custom_waveforms",
        "set_sync_all_devices",
        "update_safety",
    ];
    // Tauri generates current permissions but does not remove retired commands.
    // Keep user-authored permission files; prune only this generated directory.
    let permissions = std::path::Path::new("permissions/autogenerated");
    if permissions.exists() {
        for entry in std::fs::read_dir(permissions).expect("read generated permissions") {
            let path = entry.expect("read generated permission entry").path();
            if path
                .extension()
                .is_some_and(|extension| extension == "toml")
                && path
                    .file_stem()
                    .and_then(|stem| stem.to_str())
                    .is_some_and(|command| !COMMANDS.contains(&command))
                && std::fs::read_to_string(&path)
                    .is_ok_and(|text| text.starts_with("# Automatically generated - DO NOT EDIT!"))
                && let Err(error) = std::fs::remove_file(path)
                && error.kind() != std::io::ErrorKind::NotFound
            {
                panic!("remove retired generated permission: {error}");
            }
        }
    }
    let app_manifest = tauri_build::AppManifest::new().commands(COMMANDS);
    let attributes = tauri_build::Attributes::new().app_manifest(app_manifest);
    tauri_build::try_build(attributes).expect("failed to run Tauri build script");
}
