[package]
name = "dg-lab-link-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
dg-lab-link-plugin-sdk.workspace = true
dg-lab-link-plugin-runtime.workspace = true
futures-util.workspace = true
rustls = { version = "0.23.43", default-features = false, features = ["ring", "std"] }
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tokio-util.workspace = true
url = "2.5.8"
uuid.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
btleplug = "0.13.3"

[dev-dependencies]
tempfile = "3.27.0"
tokio = { workspace = true, features = ["test-util"] }
